
---
- name: Taskmanager Restful Apis Deployment using Ansible
  hosts: web
  become: yes

  tasks: 
    
    - name: Install NodeJs
      apt:
       name: nodejs
       state: present

    - name: Install NPM
      apt: 
       name: npm
       state: present
    
    - name: Install PM2
      npm:
       name: pm2
       global: yes

    - name: Clone Git Repo
      git:
       repo: https://github.com/sagar-18/task-manager.git
       dest: /newdata/task-manager   
    
    - name: Install Project Dependencies
      npm:
       path: /newdata/task-manager    

    - name: Start PM2 process for the API
      become_user: root
      command: /usr/local/bin/pm2 start /newdata/task-manager/task-manager-start.js --name task-manager
      
    - name: Save PM2 process list
      become_user: root
      command: pm2 save 
